import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.js'
import { formatPrice } from '../data/pricing.js'
export default function PaymentOverviewPanel({ programs }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const titles = useMemo(() => new Map(programs.map((item) => [item.id, item.title])), [programs])
  async function load() { setLoading(true); setMessage(''); if (!supabase) { setMessage('Supabase 연결 후 실제 주문·결제 현황을 확인할 수 있습니다.'); setLoading(false); return } const { data, error } = await supabase.rpc('get_edu_payment_overview'); if (error) setMessage('결제 현황을 불러오지 못했습니다. 최신 schema.sql과 관리자 권한을 확인해 주세요.'); else setItems(data || []); setLoading(false) }
  useEffect(() => { void load() }, [])
  return <div className="admin-content payment-overview"><div className="admin-toolbar"><h2>주문·결제 현황</h2><button className="button button-secondary" onClick={load} type="button">새로고침</button></div>{message && <p className="form-message" role="status">{message}</p>}<div className="admin-stats"><article><span>전체 주문</span><strong>{items.length}건</strong></article><article><span>결제 완료</span><strong>{items.filter((item) => item.order_status === 'paid').length}건</strong></article><article><span>취소·환불</span><strong>{items.filter((item) => ['cancelled','refunded'].includes(item.order_status)).length}건</strong></article></div>{loading ? <p role="status">결제 현황을 불러오고 있습니다...</p> : <div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>주문번호</th><th>사용자</th><th>프로그램</th><th>금액</th><th>주문</th><th>결제</th><th>수단</th><th>승인 시각</th></tr></thead><tbody>{items.map((item) => <tr key={item.order_id}><td>{item.order_code}</td><td>{item.user_email}</td><td>{titles.get(item.program_id) || item.program_id}</td><td>{formatPrice(item.amount)}</td><td>{item.order_status}</td><td>{item.payment_status || '-'}</td><td>{item.method || '-'}</td><td>{item.approved_at ? new Date(item.approved_at).toLocaleString('ko-KR') : '-'}</td></tr>)}</tbody></table>{items.length === 0 && <p>표시할 테스트 주문이 없습니다.</p>}</div>}</div>
}
